environment:
  matrix:
    - nodejs_version: 8
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 8
      platform: x86
      msvs_toolset: 12

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
